In [1]:
import numpy as np
import sys

Задание 1

1. Массив со значениями 1, 7, 13, 105. Посчитайте и выведите на экран размер
памяти, который он занимает. Сохраните массив в текстовый и бинарный файлы. 
Затем загрузите его и выведите на экран.

In [2]:
x = np.array([1, 7, 13, 105])
print(f"Размер занимаемой памяти: {x.size * sys.getsizeof(x.dtype)}")

np.savetxt('./data/task1.txt', x, fmt="%d")
np.save('./data/task1.npy', x)

x_txt = np.loadtxt('./data/task1.txt', dtype=np.int8)
x_bin = np.load('./data/task1.npy')

print('txt: ', x_txt)
print('bin: ', x_bin)

Размер занимаемой памяти: 384
txt:  [  1   7  13 105]
bin:  [  1   7  13 105]


2. Три массива: из 10 нулей, 10 единиц, 10 пятерок.

In [3]:
x0 = np.zeros(10, dtype=np.int8)
x1 = np.ones(10, dtype=np.int8)
x5 = np.array([5] * 10)
print(x0)
print(x1)
print(x5)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


3. Массив последовательности четных целых чисел от 30 до 70.

In [4]:
print(np.arange(30, 70, 2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


4. Массив из 10 элементов со значениями, равномерно распределенными между 5 и 
50.

In [5]:
print(np.linspace(5, 50, 10, dtype=np.int8))

[ 5 10 15 20 25 30 35 40 45 50]


5. Массив 3x3x3 из 27 случайных чисел в диапазоне от 1 до 100.

In [6]:
print(np.random.randint(1, 100, size=(3, 3, 3), dtype=np.int8))

[[[36 15 48]
  [10 42 15]
  [87 81 48]]

 [[96 92 63]
  [71 69 14]
  [24 68 72]]

 [[19 95 24]
  [30 93 50]
  [97 18 87]]]


6. Массив 3х4, заполненной значениями от 30 до 41

In [7]:
print(np.arange(30, 42).reshape(3, 4))

[[30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]]


7. Массив 10x10, в котором элементы на границах равны 1, а внутри 0.

In [8]:
x = np.ones((10, 10), dtype=np.int8)
x[1:-1, 1:-1] = 0
print(x)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


8. Массив 5x5 из нулей с элементами на главной диагонали равными 1, 2, 3, 4, 5.

In [9]:
print(np.diag(range(1, 6)))

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


9. Массив 4x4, в котором 0 и 1 расположены в шахматном порядке, с нулями на 
главной диагонали.

In [10]:
x = np.zeros((4, 4), dtype=np.int8)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


10. Массив, заполненный всеми днями марта 2017 года. Тип данных массива – дата.

In [11]:
print(np.arange('2017-03-01', '2017-03-31', dtype=np.datetime64))

['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30']


Задание 2

1. Дано два массива. Получите массив, состоящий из их общих элементов.
Например, для массивов [0 10 20 40 60] и [10 30 40] ответом будет [10, 40].

In [12]:
x1 = np.array([0, 10, 20, 40, 60], dtype=np.int8)
x2 = np.array([10, 30, 40], dtype=np.int8)
print(np.intersect1d(x1, x2))

[10 40]


2. Дан массив. Получите массив его уникальных элементов.
Исходный массив: [10 10 20 20 30 30] 
Массив его уникальных элементов: [10 20 30] 
Исходный массив: 
[[1 1] 
[2 3]] 
Массив его уникальных элементов: [1 2 3]

In [13]:
x1 = np.array([10, 10, 20, 20, 30, 30])
print(x1, '\n', np.unique(x1), '\n')
x2 = np.array([[1, 1], [2, 3]])
print(x2, '\n', np.unique(x2))

[10 10 20 20 30 30] 
 [10 20 30] 

[[1 1]
 [2 3]] 
 [1 2 3]


3.Дан массив. Получите два массива: его уникальные элементы и их частоты.
Исходный массив: [10 10 20 10 20 20 20 30 30 50 40 40]
Два массива: [10 20 30 40 50], [3 4 2 2 1]


In [15]:
x = np.array([10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])
array, period = np.unique(x, return_counts=True)
print(array, period)

[10 20 30 40 50] [3 4 2 2 1]


4.Дан массив. Получите массив путем повторения данного.
Образец массива: [1, 2, 3, 4]
Ожидаемый результат:
1 повторение
[1, 2, 3, 4]
2 повторения
[1, 2, 3, 4, 1, 2, 3, 4]
3 повторения
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [21]:
x =np.array([1, 2, 3, 4])
print(np.tile(x, (1)))
print(np.tile(x, (2)))
print(np.tile(x, (3)))


[1 2 3 4]
[1 2 3 4 1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]


5. Дан массив, в котором имеются значения nan. Получите массив, удалив все значения 
nan.
Исходный массив: [200. 300. nan nan nan 700.]
После удаления значений nan: [200. 300. 700.]
Исходный массив:
[[1. 2. 3.]
[nan 0. nan]
[6. 7. nan]]
После удаления значений nan: [1. 2. 3. 0. 6. 7.]

In [25]:
x = np.array([1, 2, 3, np.nan, 4, np.nan, 5])
print(x[~np.isnan(x)])
x = np.array([[1, 2, 3], [np.nan, 0, np.nan], [6, 7, np.nan]])
print(x[~np.isnan(x)])

[1. 2. 3. 4. 5.]
[1. 2. 3. 0. 6. 7.]


6. Дан массив. Получите массив его k наименьших значений.
Оригинальный массив: [1. 7. 8. 2. 0.1 3. 15. 2.5]
Его 4 наименьших значения: [0.1 1. 2. 2.5]

In [29]:
x = np.array([1, 7, 8, 2, 0.1, 3, 15, 2.5])
print(np.sort(x)[:4])

[0.1 1.  2.  2.5]


7. Дан массив и некоторое число. Найдите ближайший по значению к числу элемент
массива.
Исходный массив: [0.5 1.8 2.1 3.5 4.87 5.13 6.49] 
Значение для сравнения: 3,09066280756759 
Ответ: 3.5

In [30]:
x = np.array([0.5, 1.8, 2.1, 3.5, 4.87, 5.13, 6.49])
number_to_find = 3.09066280756759 
print(x.flat[np.abs(x-number_to_find).argmin()])
#Данное решение, я взял из интернета, ниже пояснение решения.
#np.falt - одномерный итератор массива, перебирающий элементы массива так будто он вектор, не зависит от размерности матрицы.
#np.argmin - возвращает индекс минимального элемента вдоль указанной оси.
#То есть, итерируемся по элементам массива, в поисках элемента, чья разница с искомым числом минимальна. Элемент возвращаем по индексу.

3.5


8. Дано два массива со строками. Получите массив при помощи поэлементного 
объединения.
1 массив: ['Python' 'PHP']
2 массив: ['Java' 'C ++']
Результат: ['Python Java' 'PHP C ++']


In [36]:
x = np.array(['Python ', 'PHP '])
y = np.array(['Java', 'C++'])
print(np.char.add(x, y))

['Python Java' 'PHP C++']


9. Дан массив строк. Получите массив с частотой встречаемости буквы «P».
Оригинальный массив: ['Python' 'PHP' 'JS' ' examples' 'html']
Количество 'P': [1 2 0 0 0]


In [40]:
x = np.array(['Python', 'PHP', 'JS', 'examples', 'html'])
print(np.vectorize(lambda a: a.count('P'))(x))

[1 2 0 0 0]


10. Найдите корни следующих полиномов: 
a. x^2 - 4х + 7
b. x^4 - 11х^3 + 9х^2 + 11х - 10

In [42]:
p1 = np.polynomial.Polynomial([1, -4, 7])
print(p1.roots())
p2 = np.polynomial.Polynomial([1, -11, 9, 11, -10])
print(p2.roots())

[0.28571429-0.24743583j 0.28571429+0.24743583j]
[-1. +0.00000000e+00j  0.1+0.00000000e+00j  1. -1.88793454e-08j
  1. +1.88793454e-08j]


Задание 3:

Напишите программу, которая будет решать систему линейных уравнений вида:
a11x + a12y = b1
a12x + a22y = b2

In [48]:
a1 = np.array(list(map(int, input('a11 a12: ').split(' '))))
b1 = np.array([int(input('b1: '))])
a2 = np.array(list(map(float, input('a12 a22: ').split(' '))))
b2 = np.array([int(input('b2: '))])

a = np.concatenate([a1, a2]).reshape([2, 2])
b = np.concatenate([b1, b2])

if np.linalg.det(a) != 0:
    x = np.linalg.solve(a, b)
    if np.allclose(np.dot(a, x), b):
        print('Solved: ', x)
else:
    print('No solutions')

Solved:  [-1.  2.]
